language: node_js
node_js:
  - 0.8
  - 0.6
script: "mocha --reporter spec --compilers coffee:coffee-script --colors --require should"
notifications:
  email:
    recipients:
    on_success: change 
    on_failure: always
