language: node_js
node_js:
  - 0.8
  - 0.6
script: "mocha --reporter spec --compilers coffee:coffee-script --colors --require should"
notifications:
  email:
    recipients:
      - pitsanu_s@hotmail.com 
    on_success: [always|never|change] # default: always 
    on_failure: [always|never|change] # default: always
